version: 2.1

orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  build:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - hold-push-fluentd-to-aliyun-pr
          filters:
            tags:
              only: /^v.*/

      - hold-push-fluentd-to-aliyun-pr:
          type: approval
          # Needed to prevent job from being triggered on master branch.
          filters:
            branches:
              ignore: master

